### ISSUE TITLE
Update to latest es6-module-transpiler

### ISSUE THREAD

**Issue by eventualbuddha** [joliss/broccoli-es6-concatenator#19]
I just updated the transpiler to v0.5.0. The API is very different. Not all features are the same (some added, some removed). Let me know if you have any trouble!

**Comment by joliss** [comment]
This plugin is deprecated now. I just updated the deprecation notice on the README:

> **This plugin is deprecated and no longer maintained,** as it uses an old version of [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler). It is recommended that you use the [broccoli-es6modules](https://github.com/ember-cli/broccoli-es6modules) plugin instead, which is based on the newer [Esperanto](http://esperantojs.org/) transpiler.

Note that the broccoli-es6modules plugin is used by Ember CLI as well.

I'm closing all issues and PRs on this repo, since I don't intend on fixing or changing anything with this plugin anymore. If anybody wants me to reopen something, please let me know. :)
