### ISSUE TITLE
Error: Invalid access to private name

### ISSUE THREAD

**Issue by aexmachina** [joliss/broccoli-es6-concatenator#20]
There's an issue with es6-module-transpiler < 0.5.0 that prevents it being loaded into a VM more than once. I've created an example of this issue here: https://github.com/aexmachina/broccoli-es6-concatenator/tree/multi-module-issue. As soon as it's `require()`d more than once it throws an error `Error: Invalid access to private name`.

This issue has been encountered in [various other places](https://github.com/mmun/broccoli-es6-module-transpiler/issues/1) as well, and the solution seems to be to upgrade to 0.5.0, but there's [no clear upgrade path](https://github.com/mmun/broccoli-es6-module-transpiler/issues/1#issuecomment-47659684) at this stage.

**Comment by joliss** [comment]
This plugin is deprecated now. I just updated the deprecation notice on the README:

> **This plugin is deprecated and no longer maintained,** as it uses an old version of [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler). It is recommended that you use the [broccoli-es6modules](https://github.com/ember-cli/broccoli-es6modules) plugin instead, which is based on the newer [Esperanto](http://esperantojs.org/) transpiler.

Note that the broccoli-es6modules plugin is used by Ember CLI as well.

I'm closing all issues and PRs on this repo, since I don't intend on fixing or changing anything with this plugin anymore. If anybody wants me to reopen something, please let me know. :)
