### ISSUE TITLE
ES5 set/get properties blown up during transpile?

### ISSUE THREAD

**Issue by blesh** [joliss/broccoli-es6-concatenator#30]
I just ran into this while upgrading to the latest Ember-CLI, and I don't have time to dig much deeper, but I wanted to report it.

I have a basic JavaScript class with property declarations like:

```js
function FooClass() {
}

FooClass.prototype = {
  get bar() {
     return this._bar;
  },

  set bar(value) {
    this._bar = value;
  },
};
```

After transpilation that becomes:

```js
function FooClass() {
}

FooClass.prototype = {
  get bar() function() {
     return this._bar;
  },

  set bar(value) function(value) {
    this._bar = value;
  },
};
```

**Comment by joliss** [comment]
This plugin is deprecated now. I just updated the deprecation notice on the README:

> **This plugin is deprecated and no longer maintained,** as it uses an old version of [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler). It is recommended that you use the [broccoli-es6modules](https://github.com/ember-cli/broccoli-es6modules) plugin instead, which is based on the newer [Esperanto](http://esperantojs.org/) transpiler.

Note that broccoli-es6modules is the plugin that Ember CLI uses now as well.

I'm closing all issues and PRs on this repo, since I don't intend on fixing or changing anything with this plugin anymore. If anybody wants me to reopen something, please let me know. :)
